import type { WitDefinition } from "../model.js";

export const AUDIT_LOG_WIT: WitDefinition = {
	referenceName: "TestVault.AuditLog",
	displayName: "TestVault Audit Log",
	description: "Immutable audit trail entry for Admin-sensitive operations. Never deleted.",
	icon: "icon_review",
	color: "#da0a00",
	isImmutableAfterCreate: true,
	fields: [
		{
			referenceName: "System.Title",
			displayName: "Operation Summary",
			type: "string",
			required: true,
		},
		{
			referenceName: "TestVault.ActorUserId",
			displayName: "Actor User ID",
			type: "string",
			required: true,
		},
		{
			referenceName: "TestVault.ActorDisplayName",
			displayName: "Actor Display Name",
			type: "string",
			required: true,
		},
		{
			referenceName: "TestVault.TimestampUtc",
			displayName: "Timestamp UTC",
			type: "dateTime",
			required: true,
		},
		{
			referenceName: "TestVault.Operation",
			displayName: "Operation",
			type: "picklistString",
			required: true,
			allowedValues: [
				"llm.provider.add",
				"llm.provider.update",
				"llm.provider.remove",
				"llm.feature.assign",
				"llm.prompt.update",
				"llm.quota.update",
				"llm.global.toggle",
				"license.update",
				"process.install",
				"process.update",
				"webhook.create",
				"webhook.delete",
				"feature_flag.update",
				"retention.update",
			],
		},
		{
			referenceName: "TestVault.ContextMetadata",
			displayName: "Context Metadata",
			type: "longText",
			required: true,
			description: "JSON-serialized Record<string, string> — never contains sensitive values",
		},
		{
			referenceName: "TestVault.OldValueAnonymized",
			displayName: "Old Value anonymized",
			type: "string",
			required: false,
			description: "Last 4 chars of the previous sensitive value only",
		},
		{
			referenceName: "TestVault.NewValueAnonymized",
			displayName: "New Value anonymized",
			type: "string",
			required: false,
			description: "Last 4 chars of the new sensitive value only",
		},
	],
	states: [{ name: "Active", color: "#da0a00", stateCategory: "InProgress" }],
	transitions: [{ from: null, to: "Active" }],
};
