import type { WitDefinition } from "../model.js";

export const TEST_CASE_WIT: WitDefinition = {
	referenceName: "TestVault.TestCase",
	displayName: "Test Case (Argos)",
	description: "Reusable test case with structured steps, priority, and automation status.",
	icon: "icon-test-case",
	color: "#00b4ef",
	fields: [
		{ referenceName: "System.Title", displayName: "Title", type: "string", required: true },
		{
			referenceName: "System.Description",
			displayName: "Description",
			type: "html",
			required: false,
		},
		{
			referenceName: "System.AreaPath",
			displayName: "Area Path",
			type: "treePath",
			required: true,
		},
		{
			referenceName: "System.IterationPath",
			displayName: "Iteration",
			type: "treePath",
			required: false,
		},
		{
			referenceName: "System.AssignedTo",
			displayName: "Assigned To",
			type: "identity",
			required: false,
		},
		{ referenceName: "System.Tags", displayName: "Tags", type: "string", required: false },
		{
			referenceName: "TestVault.Priority",
			displayName: "Priority",
			type: "picklistInteger",
			required: true,
			description: "1 = Critical, 2 = High, 3 = Medium (default), 4 = Low",
			allowedValues: [1, 2, 3, 4],
			defaultValue: 3,
		},
		{
			referenceName: "TestVault.Steps",
			displayName: "Steps",
			type: "longText",
			required: false,
			description: "JSON-serialized TestStep[] array",
		},
		{
			referenceName: "TestVault.AutomationStatus",
			displayName: "Automation Status",
			type: "picklistString",
			required: true,
			allowedValues: ["Manual", "Planned", "Automated"],
			defaultValue: "Manual",
		},
		{
			referenceName: "TestVault.AutomationKey",
			displayName: "Automation Key",
			type: "string",
			required: false,
			description: "Fully-qualified automation key for CI result matching",
		},
		{
			referenceName: "TestVault.Gherkin",
			displayName: "Gherkin",
			type: "longText",
			required: false,
			description: "BDD scenario content (Gherkin syntax)",
		},
		{
			referenceName: "TestVault.EstimatedDuration",
			displayName: "Estimated Duration (min)",
			type: "integer",
			required: false,
		},
		{
			referenceName: "TestVault.PreconditionLinks",
			displayName: "Precondition Links",
			type: "longText",
			required: false,
			description: "JSON-serialized number[] of linked Precondition WI IDs",
		},
	],
	states: [
		{ name: "Design", color: "#b2b2b2", stateCategory: "Proposed" },
		{ name: "Ready", color: "#007acc", stateCategory: "Proposed" },
		{ name: "Active", color: "#28a745", stateCategory: "InProgress" },
		{ name: "Closed", color: "#393939", stateCategory: "Completed" },
		{ name: "Deprecated", color: "#6c757d", stateCategory: "Completed" },
	],
	transitions: [
		{ from: null, to: "Design" },
		{ from: "Design", to: "Ready" },
		{ from: "Ready", to: "Active" },
		{ from: "Active", to: "Closed" },
		{ from: "Active", to: "Deprecated" },
		{ from: "Ready", to: "Deprecated" },
		{ from: "Closed", to: "Active" },
	],
};
