import type { WitDefinition } from "../model.js";

export const TEST_EXECUTION_WIT: WitDefinition = {
	referenceName: "TestVault.TestExecution",
	displayName: "TestVault Test Execution",
	description:
		"A single test run against a Test Case. Lifecycle null -> InProgress -> { Completed | Aborted }: mutable while InProgress, frozen at the application level once Completed or Aborted. Config fields fixed at creation are marked immutable per-field.",
	icon: "icon_check_box",
	color: "#ff9d00",
	fields: [
		{ referenceName: "System.Title", displayName: "Title", type: "string", required: true },
		{
			referenceName: "TestVault.TestPlanId",
			displayName: "Test Plan ID",
			type: "integer",
			required: false,
			description: "Weak reference — history preserved even if plan is deleted",
			immutable: true,
		},
		{
			referenceName: "TestVault.TestCaseId",
			displayName: "Test Case ID",
			type: "integer",
			required: true,
			description: "Strong reference — parent-child link",
			immutable: true,
		},
		{
			referenceName: "TestVault.TestCaseVersionId",
			displayName: "Test Case Version ID",
			type: "integer",
			required: false,
			description: "Set when Test Plan is Locked; references the frozen snapshot",
			immutable: true,
		},
		{
			referenceName: "TestVault.Environment",
			displayName: "Environment",
			type: "string",
			required: true,
			immutable: true,
		},
		{
			referenceName: "TestVault.GlobalStatus",
			displayName: "Global Status",
			type: "picklistString",
			required: true,
			allowedValues: ["Pass", "Fail", "Blocked", "Unexecuted", "Skipped"],
			defaultValue: "Unexecuted",
		},
		{
			referenceName: "TestVault.StepResults",
			displayName: "Step Results",
			type: "longText",
			required: false,
			description: "JSON-serialized TestStepResult[]",
		},
		{
			referenceName: "TestVault.ExecutionSource",
			displayName: "Execution Source",
			type: "picklistString",
			required: true,
			allowedValues: ["Manual", "CI"],
			defaultValue: "Manual",
			immutable: true,
		},
		{
			referenceName: "TestVault.CiPipelineRunId",
			displayName: "CI Pipeline Run ID",
			type: "string",
			required: false,
		},
		{
			referenceName: "TestVault.CiPipelineUrl",
			displayName: "CI Pipeline URL",
			type: "string",
			required: false,
		},
		{
			referenceName: "TestVault.CiPayloadHash",
			displayName: "CI Payload Hash",
			type: "string",
			required: false,
			description: "SHA-256 of the received CI payload for anti-replay",
		},
		{
			referenceName: "TestVault.DurationSeconds",
			displayName: "Duration Seconds",
			type: "integer",
			required: false,
		},
		{
			referenceName: "TestVault.Evidence",
			displayName: "Evidence",
			type: "longText",
			required: false,
			description: "JSON-serialized EvidenceRef[] (run-level)",
		},
		{
			referenceName: "TestVault.BugLinks",
			displayName: "Bug Links",
			type: "longText",
			required: false,
			description: "JSON-serialized number[] (run-level defect WI ids)",
		},
		{
			referenceName: "TestVault.GlobalStatusOverridden",
			displayName: "Global Status Overridden",
			type: "boolean",
			required: false,
			defaultValue: false,
		},
		{
			referenceName: "TestVault.PreviousExecutionId",
			displayName: "Previous Execution ID",
			type: "integer",
			required: false,
			description: "Chaining for re-run lineage",
			immutable: true,
		},
	],
	states: [
		{ name: "InProgress", color: "#007acc", stateCategory: "InProgress" },
		{ name: "Completed", color: "#393939", stateCategory: "Completed" },
		{ name: "Aborted", color: "#a4262c", stateCategory: "Removed" },
	],
	transitions: [
		{ from: null, to: "InProgress" },
		{ from: "InProgress", to: "Completed" },
		{ from: "InProgress", to: "Aborted" },
	],
};
